#
# Copyright 2017 Huawei Technologies Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
swagger: '2.0'
info:
  title: OverlayVPN Service NBI
  description: Northbound Interface for OverlayVPN
  version: 1.0.0
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: nbi-overlayvpn.open-o.org
schemes:
- http
basePath: /openoapi/sdnooverlay/v1
consumes:
  - application/json;charset=UTF-8
produces:
  - application/json;charset=UTF-8
paths:
  /vpns:
    post:
      summary: create vpn.
      description: create vpn.
      parameters:
      - name: body
        in: body
        description: vpn object to be created.
        required: true
        schema:
          type: array
          items:
            $ref: '#/definitions/NbiVpn'
      responses:
        201:
          description: create vpn success.
          schema:
            type: string
        400:
          description: create vpn failure as parameters invalid.
        401:
          description: unauthorized.
        404:
          description: create vpn failure as can't reach server.
        500:
          description: create vpn failure as inner error.

    get:
      summary: batch query vpn.
      description: batch query vpn info.
      responses:
        201:
          description: query vpn success.
          schema:
            type: string
        400:
          description: query vpn failure as parameters invalid.
        401:
          description: unauthorized.
        404:
          description: query vpn failure as can't reach server.
        500:
          description: query vpn failure as inner error.

  /vpns/{uuid}:
    get:
      summary: query vpn.
      description: query vpn info.
      parameters:
      - name: uuid
        in: path
        description: vpn ID.
        required: true
        type: string
        format: uuid
      responses:
        201:
          description: query vpn success.
          schema:
            type: string
        400:
          description: query vpn failure as parameters invalid.
        401:
          description: unauthorized.
        404:
          description: query vpn failure as can't reach server.
        500:
          description: query vpn failure as inner error.

    put:
      summary: modify vpn.
      description: modify vpn info.
      parameters:
      - name: uuid
        in: path
        description: vpn ID.
        required: true
        type: string
        format: uuid
      - name: body
        in: body
        description: vpn object to be modified.
        required: true
        schema:
          type: array
          items:
            $ref: '#/definitions/NbiVpn'
      responses:
        201:
          description: update vpn success.
          schema:
            type: string
        400:
          description: update vpn failure as parameters invalid.
        401:
          description: unauthorized.
        404:
          description: update vpn failure as can't reach server.
        500:
          description: update vpn failure as inner error.

    delete:
      summary: delete vpn.
      description: delete vpn.
      parameters:
      - name: uuid
        in: path
        description: vpn ID.
        required: true
        type: string
        format: uuid
      responses:
        201:
          description: delete vpn success.
          schema:
            type: string
        400:
          description: delete vpn failure as parameters invalid.
        401:
          description: unauthorized.
        404:
          description: delete vpn failure as can't reach server.
        500:
          description: delete vpn failure as inner error.

  /vpns/{uuid}/action/deploy:
    post:
      summary: deploy vpn.
      description: deploy all connections in the vpn.
      parameters:
      - name: uuid
        in: path
        description: vpn ID.
        required: true
        type: string
        format: uuid
      responses:
        201:
          description: deploy vpn success.
          schema:
            type: string
        400:
          description: deploy vpn failure as parameters invalid.
        401:
          description: unauthorized.
        404:
          description: deploy vpn failure as can't reach server.
        500:
          description: deploy vpn failure as inner error.

  /vpns/{uuid}/action/undeploy:
    post:
      summary: undeploy vpn.
      description: undeploy all connections in the vpn.
      parameters:
      - name: uuid
        in: path
        description: vpn ID.
        required: true
        type: string
        format: uuid
      responses:
        201:
          description: undeploy vpn success.
          schema:
            type: string
        400:
          description: undeploy vpn failure as parameters invalid.
        401:
          description: unauthorized.
        404:
          description: undeploy vpn failure as can't reach server.
        500:
          description: undeploy vpn failure as inner error.

  /vpn-connections:
    post:
      summary: create vpn connection
      description: create vpn connection.
      parameters:
      - name: body
        in: body
        description: vpn connection object to be created.
        required: true
        schema:
          type: array
          items:
            $ref: '#/definitions/NbiVpnConnection'
      responses:
        201:
          description: create vpn connection success.
          schema:
            type: object
        400:
          description: create vpn connection failure as parameters invalid.
        401:
          description: unauthorized.
        404:
          description: create vpn connection failure as can't reach server.
        500:
          description: create vpn connection failure as inner error.

    get:
      summary: batch query vpn connection
      description: batch query vpn connection.
      responses:
        201:
          description: query vpn connection success.
          schema:
            type: string
        400:
          description: query vpn connection failure as parameters invalid.
        401:
          description: unauthorized.
        404:
          description: query vpn connection failure as can't reach server.
        500:
          description: query vpn connection failure as inner error.

  /vpn-connections/{uuid}:
    put:
      summary: modify vpn connection
      description: modify vpn connection.
      parameters:
      - name: uuid
        in: path
        description: vpn connection ID.
        required: true
        type: string
        format: uuid
      - name: body
        in: body
        description: vpn connection object to be modified.
        required: true
        schema:
          type: array
          items:
            $ref: '#/definitions/NbiVpnConnection'
      responses:
        201:
          description: modify vpn connection success.
          schema:
            type: string
        400:
          description: modify vpn connection failure as parameters invalid.
        401:
          description: unauthorized.
        404:
          description: modify vpn connection failure as can't reach server.
        500:
          description: modify vpn connection failure as inner error.

    get:
      summary: query single vpn connection
      description: query single vpn connection.
      parameters:
      - name: uuid
        in: path
        description: vpn connection ID.
        required: true
        type: string
        format: uuid
      responses:
        201:
          description: query vpn connection success.
          schema:
            type: string
        400:
          description: query vpn connection failure as parameters invalid.
        401:
          description: unauthorized.
        404:
          description: query vpn connection failure as can't reach server.
        500:
          description: query vpn connection failure as inner error.

    delete:
      summary: delete vpn connection
      description: delete vpn connection.
      parameters:
      - name: uuid
        in: path
        description: vpn connection ID.
        required: true
        type: string
        format: uuid
      responses:
        201:
          description: delete vpn connection success.
          schema:
            type: string
        400:
          description: delete vpn connection failure as parameters invalid.
        401:
          description: unauthorized.
        404:
          description: delete vpn connection failure as can't reach server.
        500:
          description: delete vpn connection failure as inner error.

  /vpn-connections/{uuid}/action/deploy:
    post:
      summary: deploy vpn connection.
      description: deploy vpn connection.
      parameters:
      - name: uuid
        in: path
        description: vpn connection ID.
        required: true
        type: string
        format: uuid
      responses:
        201:
          description: deploy vpn connection success.
          schema:
            type: string
        400:
          description: deploy vpn connection failure as parameters invalid.
        401:
          description: unauthorized.
        404:
          description: deploy vpn connection failure as can't reach server.
        500:
          description: deploy vpn connection failure as inner error.

  /vpn-connections/{uuid}/action/undeploy:
    post:
      summary: undeploy vpn connection.
      description: undeploy vpn connection.
      parameters:
      - name: uuid
        in: path
        description: vpn connection ID.
        required: true
        type: string
        format: uuid
      responses:
        201:
          description: undeploy vpn connection success.
          schema:
            type: string
        400:
          description: undeploy vpn connection failure as parameters invalid.
        401:
          description: unauthorized.
        404:
          description: undeploy vpn connection failure as can't reach server.
        500:
          description: undeploy vpn connection failure as inner error.

  /vpn-gateways:
    get:
      summary: batch query vpn gateways
      description: batch query vpn gateways.
      responses:
        201:
          description: query vpn gateways success.
          schema:
            type: string
        400:
          description: query vpn gateways failure as parameters invalid.
        401:
          description: unauthorized.
        404:
          description: query vpn gateways failure as can't reach server.
        500:
          description: query vpn gateways failure as inner error.

    post:
      summary: create vpn gateway
      description: create vpn gateway.
      parameters:
      - name: body
        in: body
        description: vpn gateway object to be created.
        required: true
        schema:
          type: array
          items:
            $ref: '#/definitions/NbiVpnGateway'
      responses:
        201:
          description: create vpn gateway success.
          schema:
            type: object
        400:
          description: create vpn gateway failure as parameters invalid.
        401:
          description: unauthorized.
        404:
          description: create vpn gateway failure as can't reach server.
        500:
          description: create vpn gateway failure as inner error.

  /vpn-gateways/{uuid}:
    get:
      summary: query single vpn gateway
      description: query single vpn gateway.
      parameters:
      - name: uuid
        in: path
        description: vpn gateway ID.
        required: true
        type: string
        format: uuid
      responses:
        201:
          description: query vpn gateway success.
          schema:
            type: string
        400:
          description: query vpn gateway failure as parameters invalid.
        401:
          description: unauthorized.
        404:
          description: query vpn gateway failure as can't reach server.
        500:
          description: query vpn gateway failure as inner error.

    delete:
      summary: delete vpn gateway
      description: delete vpn gateway.
      parameters:
      - name: uuid
        in: path
        description: vpn gateway ID.
        required: true
        type: string
        format: uuid
      responses:
        201:
          description: delete vpn gateway success.
          schema:
            type: string
        400:
          description: delete vpn gateway failure as parameters invalid.
        401:
          description: unauthorized.
        404:
          description: delete vpn gateway failure as can't reach server.
        500:
          description: delete vpn gateway failure as inner error.

    put:
      summary: modify vpn gateway
      description: modify vpn gateway.
      parameters:
      - name: uuid
        in: path
        description: vpn gateway ID.
        required: true
        type: string
        format: uuid
      - name: body
        in: body
        description: vpn gateway object to be modified.
        required: true
        schema:
          type: array
          items:
            $ref: '#/definitions/NbiVpnGateway'
      responses:
        201:
          description: modify vpn gateway success.
          schema:
            type: object
        400:
          description: modify vpn gateway failure as parameters invalid.
        401:
          description: unauthorized.
        404:
          description: modify vpn gateway failure as can't reach server.
        500:
          description: modify vpn gateway failure as inner error.

definitions:
  NbiVpn:
    description: vpn model
    allOf:
    - $ref: '#/definitions/UuidModel'
    - type: object
      properties:
        name:
          type: string
        tenantId:
          type: string
          format: uuid
        description:
          type: string
        vpnDescriptor:
          type: string
          description: vpn template name

  NbiVpnConnection:
    description: vpn connection model
    allOf:
    - $ref: '#/definitions/UuidModel'
    - type: object
      properties:
        name:
          type: string
        tenantId:
          type: string
          format: uuid
        description:
          type: string
        deployStatus:
          type: string
          description: deploy status(deploy,undeploy)
        vpnId:
          type: string
        aEndVpnGatewayId:
          type: string
        zEndVpnGatewayId:
          type: string
        vni:
          type: string

  NbiVpnGateway:
    description: vpn gateway model
    allOf:
    - $ref: '#/definitions/UuidModel'
    - type: object
      properties:
        name:
          type: string
        tenantId:
          type: string
          format: uuid
        description:
          type: string
        vpnId:
          type: string
        siteId:
          type: string
        vpcId:
          type: string
        deployPosition:
          type: string
        upstreamBandwidth:
          type: string
        downstreamBandwidth:
          type: string
        vlans:
          type: string
        ports:
          description: uuid list of LAN ports
          type: array
          items:
            type: string
        portNames:
          description: name list of LAN ports
          type: array
          items:
            type: string
        regionId:
          type: string
  UuidModel:
    description: base model
    type: object
    properties:
      uuid:
        type: string
        format: uuid