#
# Copyright 2017 Huawei Technologies Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
swagger: '2.0'
info:
  title: Ipsec Service NBI
  description: Northbound Interface for Ipsec
  version: 1.0.0
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: nbi-ipsec.open-o.org
schemes:
- http
basePath: /openoapi/sdnoipsec/v1
consumes:
- application/json;charset=UTF-8
produces:
- application/json;charset=UTF-8
paths:
  /ipsec-connections:
    post:
      summary: create Ipsec.
      description: create Ipsec.
      parameters:
      - name: body
        in: body
        description: Ipsec object to be created.
        required: true
        schema:
          type: array
          items:
            $ref: '#/definitions/NbiIpSec'
      responses:
        201:
          description: create Ipsec success.
          schema:
            type: array
            items:
              $ref: '#/definitions/NbiIpSec'
        400:
          description: create Ipsec failure as parameters invalid.
        401:
          description: unauthorized.
        404:
          description: create Ipsec failure as can't reach server.
        500:
          description: create Ipsec failure as inner error.
    put:
      summary: update Ipsec.
      description: update Ipsec.
      parameters:
      - name: body
        in: body
        description: Ipsec object to be created.
        required: true
        schema:
          type: array
          items:
            $ref: '#/definitions/NbiIpSec'
      responses:
        201:
          description: update Ipsec success.
          schema:
            type: array
            items:
              $ref: '#/definitions/NbiIpSec'
        400:
          description: update Ipsec failure as parameters invalid.
        401:
          description: unauthorized.
        404:
          description: update Ipsec failure as can't reach server.
        500:
          description: update Ipsec failure as inner error.
  /ipsec-connections/{ipsecConnectionId}:
    get:
      summary: query Ipsec.
      description: query Ipsec info.
      parameters:
      - name: ipsecConnectionId
        in: path
        description: Ipsec connection ID.
        required: true
        type: string
        format: uuid
      responses:
        200:
          description: query Ipsec success.
          schema:
            $ref: '#/definitions/NbiIpSec'
        400:
          description: query Ipsec failure as parameters invalid.
        401:
          description: unauthorized.
        404:
          description: query Ipsec failure as can't reach server.
        500:
          description: query Ipsec failure as inner error.
    delete:
      summary: delete Ipsec.
      description: delete Ipsec.
      parameters:
      - name: ipsecConnectionId
        in: path
        description: Ipsec connection ID.
        required: true
        type: string
        format: uuid
      responses:
        201:
          description: delete Ipsec success.
          schema:
            type: string
        400:
          description: delete Ipsec failure as parameters invalid.
        401:
          description: unauthorized.
        404:
          description: delete Ipsec failure as can't reach server.
        500:
          description: delete Ipsec failure as inner error.
  /ipsec-connections/action:
    post:
      summary: deploy or undeploy Ipsec.
      description: deploy or undeploy Ipsec.
      parameters:
      - name: body
        in: body
        description: List of UUIDs.
        required: true
        schema:
          $ref: '#/definitions/NbiActionModel'
      responses: 
        201:
          description: deploy or undeploy Ipsec success.
          schema:
            type: array
            items: 
              type: string
        400:
          description: deploy or undeploy Ipsec failure as parameters invalid.
        401:
          description: unauthorized.
        404:
          description: deploy or undeploy Ipsec failure as can't reach server.
        500:
          description: deploy or undeploy Ipsec failure as inner error.
  /ipsec-connections/batch-query:
    post:
      summary: batch query Ipsec.
      description: batch query Ipsec.
      parameters:
      - name: body
        in: body
        description: Ipsec UUIDs to be queried. 
        required: true
        schema:
          type: array
          items: 
            type: string
      responses: 
        200:
          description: query Ipsec success.
          schema:
            type: array
            items:
              $ref: '#/definitions/NbiIpSec'
        400:
          description: query Ipsec failure as parameters invalid.
        401:
          description: unauthorized.
        404:
          description: query Ipsec failure as can't reach server.
        500:
          description: query Ipsec failure as inner error.
definitions:
  NbiIpSec:
    description: NBI IpSec model
    allOf:
    - $ref: '#/definitions/BaseModel'
    - type: object
      required:
      - srcNeId
      - connectionId
      - srcNeRole
      - destNeRole
      - type
      - destNeId
      - workType
      - protectionPolicy
      - ikePolicy
      - ipsecPolicy
      - srcIsTemplateType
      - destIsTemplateType
      properties:
        srcNeId:
          type: string
        connectionId:
          type: string
          format: uuid
        srcNeRole:
          type: string
          description: localcpe,cloudcpe,vpc
        destNeRole:
          type: string
          description: localcpe,cloudcpe,vpc
        type:
          type: string
          description: ipsec,ipv6_over_ipv4,ipv4_over_ipv6
        destNeId:
          type: string
        srcPortName:
          type: string
        destPortName:
          type: string
        workType:
          type: string
          description: work,protect
        protectionPolicy:
          type: string
          description: nqa,none
        nqa:
          type: string
        ikePolicy:
          type: string
        ipsecPolicy:
          type: string
        srcIsTemplateType:
          type: string
          description: boolean(true,false)
        destIsTemplateType:
          type: string
          description: boolean(true,false)
        ruleSrcPortName:
          type: string
        ruleDestPortName:
          type: string
        sourceLanCidrs:
          type: string
        destLanCidrs:
          type: string
        qosPreClassify:
          type: string
          description: boolean(true,false)
        regionId:
          type: string
        srcPortIp:
          type: string  
        destPortIp:
          type: string
  NbiActionModel:
    type: object
    description: action model
    properties:
      deploy:
        description: list of UUIDs
        type: array
        items:
          type: string
      undeploy:
        description: list of UUIDs
        type: array
        items:
          type: string
      
  UuidModel:
    description: uuid
    type: object
    properties:
      id:
        type: string
        format: uuid
  BaseModel:
    description: base model
    allOf:
    - $ref: '#/definitions/UuidModel'
    - type: object
      required:
      - deployStatus
      properties:
        tenantId:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        additionalInfo:
          type: string
        deployStatus:
          type: string
          description: deploy status(deploy,undeploy)
        actionState:
          type: string
          description: action state(none,normal,creating,create_exception,deleting,delete_exception,updating,update_exception,deploying,deploy_exception)
        activeStatus:
          type: string
          description: active status(none,active,inactive,partially_inactive)
        runningStatus:
          type: string
          description: running status(none,up,down,partially_down)
 